{{- if .Values.adminService.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ambassador.fullname" . }}-admin
  labels:
    app: {{ template "ambassador.name" . }}
    chart: {{ template "ambassador.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.adminService.type }}
  ports:
    - port: 8877
      targetPort: admin
      protocol: TCP
      name: admin
      {{- if (and (eq .Values.adminService.type "NodePort") (not (empty .Values.adminService.nodePort))) }}
      nodePort: {{ .Values.adminService.nodePort }}
      {{- end }}
  selector:
    app: {{ template "ambassador.name" . }}
    release: {{ .Release.Name }}
{{- end -}}
