apiVersion: v1
kind: Service
metadata:
  name: {{ template "ambassador.fullname" . }}
  labels:
    app: {{ template "ambassador.name" . }}
    chart: {{ template "ambassador.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.service.loadBalancerIP }}"
{{- end }}
  ports:
    {{- if .Values.service.enableHttp }}
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
      {{- with .Values.service.httpNodePort }}
      nodePort: {{ toYaml . }}
      {{- end }}
    {{- end }}
    {{- if .Values.service.enableHttps }}
    - port: {{ .Values.service.httpsPort }}
      targetPort: https
      protocol: TCP
      name: https
      {{- with .Values.service.httpsNodePort }}
      nodePort: {{ toYaml . }}
      {{- end }}
    {{- end }}
  selector:
    app: {{ template "ambassador.name" . }}
    release: {{ .Release.Name }}
{{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml . | indent 4 }}
{{- end }}